@startuml

class NameSorter {
    String inputPath
    String outputPath
    Names names

    readNames()
    writeNames()
    createFileIfDoesntExist()
}

class Names {
    ArrayList<String> nameList

    setNameList()
    getNameList()
    sortNameList()
    size()
}

NameSorter o-- Names

@enduml