@startuml

class NameSorter {
    String inputPath
    String outputPath
    Names names

    readNames()
    writeNames()
    createFileIfDoesntExist()
}

class Names {
    ArrayList<String> nameList

    setNameList()
    getNameList()
    sortNamesList()
    size()
}

NameSorter o-- Names

@enduml

' Each class within your diagram must list both the
' attributes and the methods defined within that class.