@startuml

class WordFinder {
    String inputPath
    String outputPath
    ArrayList<String> phraseList
    String outputFileName

    readPhrases()
    writePhrases()
    createFileIfDoesntExist()
    replaceOccurrences()
}

@enduml