@startuml

class WordFrequencyFinder {
    String inputPath
    ArrayList<String> phraseList

    readPhrases()
    countOccurrences()
    sortHashMap()
    displayWordOccurrencesHistogram()
    convertIntToAsterisks()
}

@enduml